### ISSUE TITLE
MultiMA_TSL3b name 'tv_hma' is not defined

### ISSUE THREAD

**Issue by sleeplezz1** [stash86/MultiMA_TSL#7]
If i want to run your strategy from patreon i get this error every time:

`Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 931, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 868, in backtest_one_strategy
    results = self.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 731, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 278, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 940, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/freqtrade/user_data/strategies/MultiMA_TSL3b.py", line 300, in populate_buy_trend
    dataframe['hma_offset_buy'] = tv_hma(dataframe, int(self.base_nb_candles_buy_hma.value)) *self.low_offset_hma.value
NameError: name 'tv_hma' is not defined`

**Comment by stash86** [comment]
sorry, let me fix that quickly

**Comment by stash86** [comment]
fixed

**Comment by sleeplezz1** [comment]
So can you send me the new version via email ? otherwise i have to pax again 

Thank you in advance :) 

Von meinem iPhone gesendet

**Comment by stash86** [comment]
According to patreon dashboard, you didn't get charged for that first download. Not sure how, but it showed $0

**Comment by sleeplezz1** [comment]
I already got charged for the first download ;) 
so is there any way to contact you private ?

**Comment by stash86** [comment]
discord?
